import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { InquiryForm } from "@/components/InquiryForm";
import { PageHero } from "@/components/PageHero";
import { isLocale, localePath } from "@/lib/i18n";
import { pageMetadata } from "@/lib/page-metadata";
import { siteConfig } from "@/lib/site";

const faqs = [["What should I include in an enquiry?", "Share your material or process, application, installation constraints, required quantity and any drawings or photos that help clarify the scope."], ["Can I ask for help selecting equipment?", "Yes. Start with your process conditions and intended outcome; equipment suitability is reviewed against the supplied information."], ["Do you show public prices?", "No. A quotation is prepared after the equipment scope and project requirements are reviewed."]];
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const { locale } = await params; return isLocale(locale) ? pageMetadata({ locale, path: "contact", title: "Contact BZMAGNET", description: "Contact BZMAGNET to discuss industrial magnetic separation equipment requirements." }) : {}; }
export default async function Page({ params }: { params: Promise<{ locale: string }> }) { const { locale } = await params; if (!isLocale(locale)) notFound(); const { email, whatsapp, address } = siteConfig.contact; return <><PageHero eyebrow="Contact" title="Talk Through Your Process" intro="Share the process conditions and project requirements that matter to your equipment review."/><section className="section section-white"><div className="shell contact-page-grid"><div><h2>Contact details</h2><dl className="contact-details"><div><dt>Email</dt><dd>{email ? <a href={`mailto:${email}`}>{email}</a> : "Email placeholder — configure verified contact details."}</dd></div><div><dt>WhatsApp</dt><dd>{whatsapp || "WhatsApp placeholder — configure verified contact details."}</dd></div><div><dt>Factory Address</dt><dd>{address || "Factory address placeholder — configure verified address."}</dd></div><div><dt>Business Hours</dt><dd>Business hours placeholder — confirm before publication.</dd></div></dl><div className="map-placeholder" role="img" aria-label="Static map placeholder; configure a verified map before embedding">Verified map location placeholder</div></div><div><span className="eyebrow">Contact Form</span><h2>Send your project details</h2><InquiryForm variant="contact" locale={locale}/></div></div></section><section className="section"><div className="shell prose"><span className="eyebrow">FAQ</span><h2>Before you send an enquiry</h2><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></div></section><section className="band"><div className="shell band-row"><div><h2>Ready to discuss your equipment scope?</h2><p>Send the application and project requirements for a practical review.</p></div><Link className="btn btn-primary" href={localePath(locale, "request-quote")}>Request a Quote</Link></div></section></>; }
