import Image from "next/image";
import Link from "next/link";
import { type Article, articlePath, editorialAssets } from "@/lib/editorial";
import { absoluteUrl, siteConfig } from "@/lib/site";
import { JsonLd } from "./JsonLd";

export function ArticleRenderer({ article }: { article: Article }) {
  const hero = article.hero ? editorialAssets[article.hero.assetId as keyof typeof editorialAssets] : undefined;
  const path = articlePath(article);
  const breadcrumbs = [{ name: "Home", url: absoluteUrl(`/${article.locale}/`) }, { name: article.contentType === "blog" ? "Blog" : "News", url: absoluteUrl(`/${article.locale}/${article.contentType === "blog" ? "blog" : "news"}`) }, { name: article.title, url: absoluteUrl(path) }];
  return <>
    <JsonLd data={{ "@context": "https://schema.org", "@type": "Article", headline: article.title, description: article.summary, datePublished: article.publishedAt, dateModified: article.modifiedAt || article.publishedAt, author: { "@type": "Organization", name: article.author.name }, publisher: { "@type": "Organization", name: siteConfig.name, url: siteConfig.url }, mainEntityOfPage: absoluteUrl(path), ...(hero ? { image: absoluteUrl(hero.src) } : {}) }} />
    <JsonLd data={{ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: breadcrumbs.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.name, item: item.url })) }} />
    <article className="article">
      <div className="article-head"><nav aria-label="Breadcrumb"><Link href={`/${article.locale}/`}>Home</Link> / <Link href={`/${article.locale}/${article.contentType === "blog" ? "blog" : "news"}`}>{article.contentType === "blog" ? "Blog" : "News"}</Link></nav><span className="eyebrow">{article.contentType.replace("_", " ")}</span><h1>{article.title}</h1><p className="article-summary">{article.summary}</p><div className="article-meta"><time>{article.publishedAt}</time><Link href={article.author.profilePath || `/${article.locale}/editorial-policy`}>{article.author.name}</Link></div></div>
      {hero && <figure className="article-hero"><Image src={hero.src} alt={article.hero!.alt} width={1536} height={1024} priority sizes="(max-width:900px) 100vw, 900px"/><figcaption>{article.hero?.caption}</figcaption></figure>}
      <div className="article-layout"><aside className="article-toc"><strong>On this page</strong>{article.sections.filter((section) => section.level === 2).map((section) => <a key={section.heading} href={`#${slug(section.heading)}`}>{section.heading}</a>)}</aside><div className="article-copy">{article.sections.map((section) => { const Tag = section.level === 2 ? "h2" : "h3"; return <section key={section.heading}><Tag id={slug(section.heading)}>{section.heading}</Tag>{section.blocks.map((block, index) => <BlockView key={index} block={block}/>)}</section>; })}{article.contentType === "industry_news" && article.sources.length > 0 && <section><h2>Sources</h2><ul>{article.sources.map((source) => <li key={source.url}><a href={source.url} rel="nofollow noopener">{source.publisher}: {source.title}</a> ({source.publishedAt})</li>)}</ul></section>}{article.faq.length > 0 && <section><h2>Frequently Asked Questions</h2>{article.faq.map((item) => <details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</section>}<div className="article-cta"><h2>{article.cta.label}</h2><p>{article.cta.text}</p><Link className="btn btn-orange" href={article.cta.href}>{article.cta.label}</Link></div></div></div>
    </article>
  </>;
}
function slug(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, "-"); }
function BlockView({ block }: { block: Article["sections"][number]["blocks"][number] }) { if (block.type === "paragraph") return <p>{block.text}</p>; if (block.type === "bullets" || block.type === "checklist") return <ul>{block.items.map((item) => <li key={item}>{item}</li>)}</ul>; if (block.type === "numbered") return <ol>{block.items.map((item) => <li key={item}>{item}</li>)}</ol>; if (block.type === "callout") return <aside className={`article-callout ${block.tone}`}><strong>{block.title}</strong><p>{block.text}</p></aside>; if (block.type === "table") return <div className="table-wrap"><table><thead><tr>{block.columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{block.rows.map((row, rowIndex) => <tr key={rowIndex}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>; return null; }
