"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { cloneElement, isValidElement, useId, useMemo, useState, type ReactNode } from "react";
import { useForm } from "react-hook-form";
import { inquirySchema, productCategories, type InquiryInput } from "@/lib/inquiry-schema";

type Props = { variant: "quick" | "product" | "rfq" | "contact"; productCategory?: string; productModel?: string; productUrl?: string; locale?: string };
const category = (value?: string) => productCategories.includes(value as never) ? value as InquiryInput["productCategory"] : "Other / Not sure";

export function InquiryForm({ variant, productCategory, productModel, productUrl, locale = "en" }: Props) {
  const [status, setStatus] = useState<"idle" | "success" | "error">("idle"); const [message, setMessage] = useState("");
  const form = useForm<InquiryInput>({ resolver: zodResolver(inquirySchema), defaultValues: { fullName: "", companyName: "", country: "", businessEmail: "", productCategory: category(productCategory), message: "", phone: "", productModel: productModel || "", application: "", requiredQuantity: "", technicalRequirement: "", productUrl: productUrl || "", formType: variant, website: "" } });
  // React Hook Form owns this subscription; it is not passed into memoized children.
  // eslint-disable-next-line react-hooks/incompatible-library
  const selected = form.watch("productCategory");
  const technicalLabel = useMemo(() => selected.includes("Conveyor") || selected.includes("Mineral") ? "Required Capacity / Throughput" : selected.includes("Process") ? "Required Pressure / Capacity" : "Required Technical Detail", [selected]);
  const compact = variant === "quick";
  async function submit(values: InquiryInput) { setStatus("idle"); setMessage(""); try { const response = await fetch("/api/inquiry", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(values) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Submission failed."); setStatus("success"); setMessage(data.message); form.reset({ ...values, website: "" }); } catch (error) { setStatus("error"); setMessage(error instanceof Error ? error.message : "Unable to submit the enquiry."); } }
  if (status === "success" && variant === "rfq") return <div className="form-success" role="status"><h2>Your request has been received.</h2><p>{message}</p><a className="btn btn-primary" href={`/${locale}/products`}>Return to products</a><a className="btn btn-secondary" href="https://wa.me/" target="_blank" rel="noreferrer">WhatsApp Us</a></div>;
  return <form className={`inquiry-form inquiry-${variant}`} onSubmit={form.handleSubmit(submit)} noValidate><input type="hidden" {...form.register("formType")} /><div className="honeypot" aria-hidden="true"><label>Website<input tabIndex={-1} autoComplete="off" {...form.register("website")} /></label></div><fieldset><legend>{compact ? "Quick Inquiry" : "Contact Details"}</legend><Field label="Full Name" error={form.formState.errors.fullName?.message}><input autoComplete="name" {...form.register("fullName")} /></Field><Field label="Company Name" error={form.formState.errors.companyName?.message}><input autoComplete="organization" {...form.register("companyName")} /></Field><Field label="Country" error={form.formState.errors.country?.message}><input autoComplete="country-name" {...form.register("country")} /></Field><Field label="Business Email" error={form.formState.errors.businessEmail?.message}><input type="email" autoComplete="email" {...form.register("businessEmail")} /></Field>{!compact && <Field label="WhatsApp / Phone"><input autoComplete="tel" {...form.register("phone")} /></Field>}</fieldset>{!compact && <fieldset><legend>Equipment Requirements</legend><Field label="Product Category" error={form.formState.errors.productCategory?.message}><select {...form.register("productCategory")}>{productCategories.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Product Model"><input readOnly={variant === "product"} {...form.register("productModel")} /></Field><Field label="Required Quantity"><input {...form.register("requiredQuantity")} /></Field><Field label={technicalLabel}><input {...form.register("technicalRequirement")} /></Field><p className="file-placeholder">File upload placeholder: share drawings or process photos after contact is confirmed.</p></fieldset>}<fieldset><legend>Project Details</legend>{!compact && <Field label="Application"><input {...form.register("application")} /></Field>}<Field label="Message" error={form.formState.errors.message?.message} wide><textarea {...form.register("message")} placeholder="Tell us about your application and requirements." /></Field></fieldset>{status !== "idle" && <p className={`form-message ${status}`} role={status === "error" ? "alert" : "status"} aria-live={status === "error" ? "assertive" : "polite"}>{message}</p>}<button className="btn btn-primary" type="submit" disabled={form.formState.isSubmitting}>{form.formState.isSubmitting ? "Submitting…" : compact ? "Send Quick Inquiry" : "Submit Enquiry"}</button></form>;
}
function Field({ label, error, wide, children }: { label: string; error?: string; wide?: boolean; children: ReactNode }) { const errorId = useId(); const control = isValidElement(children) ? cloneElement(children, { "aria-invalid": Boolean(error) || undefined, "aria-describedby": error ? errorId : undefined } as Record<string, unknown>) : children; return <label className={`field${wide ? " full" : ""}`}>{label}{control}{error && <small id={errorId} role="alert">{error}</small>}</label>; }
