import Link from "next/link";
import { InquiryForm } from "./InquiryForm";
import { JsonLd } from "./JsonLd";
import { ProductGallery } from "./ProductGallery";
import { Locale, localePath } from "@/lib/i18n";
import { ProductRecord, productPath, visibleRows } from "@/lib/product-model";
import { absoluteUrl, siteConfig } from "@/lib/site";

export function ProductDetail({ product, locale }: { product: ProductRecord; locale: Locale }) {
  const l = product.locale[locale]; const images = product.media.filter((item) => item.type === "product" && item.approved && !item.aiGenerated); const specs = visibleRows(product.specifications); const options = visibleRows(product.options);
  const quote = `${localePath(locale, "request-quote")}?product=${encodeURIComponent(l.title)}&category=${encodeURIComponent(product.familyLabel)}&context=product-detail`;
  const productUrl = absoluteUrl(productPath(locale, l.slug)); const crumbs = [{ name: "Home", url: absoluteUrl(`/${locale}/`) }, { name: "Products", url: absoluteUrl(`/${locale}/products`) }, { name: product.familyLabel, url: absoluteUrl(`/${locale}/products`) }, { name: l.title, url: productUrl }];
  const publicSpecifications = specs.filter((item) => item.display !== "Available on request").map((item) => ({ "@type": "PropertyValue", name: item.label, value: item.display }));
  return <><JsonLd data={{ "@context": "https://schema.org", "@type": "Product", name: l.title, description: l.summary, url: productUrl, category: product.familyLabel, brand: { "@type": "Brand", name: siteConfig.name }, ...(publicSpecifications.length ? { additionalProperty: publicSpecifications } : {}) }} /><JsonLd data={{ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: crumbs.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.name, item: item.url })) }} />{product.faq.length > 0 && <JsonLd data={{ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: product.faq.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) }} />}
    <nav className="shell product-breadcrumbs" aria-label="Breadcrumb">{crumbs.map((item, index) => <span key={item.url}>{index > 0 && " / "}<Link href={item.url}>{item.name}</Link></span>)}</nav>
    <section className="product-hero"><div className="shell product-hero-grid"><div><span className="eyebrow">{product.familyLabel}</span><h1>{l.title}</h1><p className="product-summary">{l.summary}</p><div className="application-tags">{product.applications.slice(0, 4).map((item) => <span key={item.title}>{item.title}</span>)}</div><div className="actions"><Link className="btn btn-orange" href={quote}>Request a Quote</Link><Link className="btn btn-outline" href={`${quote}&details=1`}>Send Process Details</Link></div></div><div>{images.length ? <ProductGallery images={images} locale={locale} /> : <div className="product-placeholder" role="img" aria-label="Product image available on request"><span>Image available on request</span></div>}</div></div></section>
    <div className="shell quick-info">{[["Suitable process", product.applications[0]?.context], ["Equipment type", product.productType], ["Installation position", specs.find((item) => item.label === "Installation position")?.display], ["Operating mode", specs.find((item) => item.label === "Cleaning mode")?.display]].map(([label, value]) => <div key={label}><strong>{label}</strong><span>{value || "Available on request"}</span></div>)}</div>
    <nav className="detail-nav" aria-label="Product details"><div className="shell">{[["overview", "Overview"], ["working-principle", "How It Works"], ["applications", "Applications"], ["selection", "Selection Information"], ["specifications", "Specifications"], ["installation", "Installation"], ["faq", "FAQ"]].map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</div></nav>
    <div className="shell product-body"><main><Section id="overview" title="Overview"><p>{l.description}</p>{product.limitations[0] && <p>{product.limitations[0]}</p>}</Section><Section id="working-principle" title="How It Works"><p>{product.capabilities.join(" ")}</p></Section><Section id="applications" title="Applications"><div className="application-grid">{product.applications.map((item) => <article key={item.title}><h3>{item.title}</h3><p>{item.context}</p><dl><dt>Placement</dt><dd>{item.placement}</dd><dt>Material</dt><dd>{item.material}</dd></dl></article>)}</div></Section><Section id="selection" title="Information Needed for Product Matching"><ul className="selection-list">{product.selectionInputs.map((item) => <li key={item}>{item}</li>)}</ul><p className="notice">The suitable configuration is confirmed after reviewing the process information provided.</p></Section><Section id="specifications" title="Specifications"><InfoTable rows={specs} /><div className="option-card"><h3>Options and Customisation</h3>{options.length ? <InfoTable rows={options} /> : <p>Please send project requirements for confirmation.</p>}</div></Section><Section id="installation" title="Installation and Use"><ol className="install-steps"><li><strong>Confirm position</strong><span>Review the intended process position.</span></li><li><strong>Confirm clearance and support</strong><span>Provide installation space and mounting constraints.</span></li><li><strong>Confirm power/control requirements</strong><span>Share available services and control preferences.</span></li></ol><div className="considerations"><h3>Important considerations</h3><ul>{product.limitations.map((item) => <li key={item}>{item}</li>)}</ul></div><h3>Maintenance</h3>{product.maintenance?.length ? <ul>{product.maintenance.map((item) => <li key={item}>{item}</li>)}</ul> : <p>Request maintenance guidance for the configuration under review.</p>}</Section><Section id="related" title="Related Planning"><div className="related-links"><Link href={localePath(locale,"industry-solutions")}>Review industry solutions</Link><Link href={localePath(locale,"resources")}>Read selection resources</Link><Link href={localePath(locale,"products")}>Compare equipment families</Link></div></Section><Section id="faq" title="Frequently Asked Questions"><div className="faq-list">{product.faq.map((item) => <details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</div></Section></main><aside className="sticky-enquiry"><h2>Start Your Enquiry</h2><p>{l.title}</p><p>Share the application, installation details and required quantity for product matching.</p><InquiryForm variant="product" productCategory={product.familyLabel} productModel={l.title} productUrl={productUrl} locale={locale} /></aside></div>
    <section className="product-final"><div className="shell"><div><h2>Need Help Reviewing This Equipment?</h2><p>Send your material and process details. We will help you review suitable equipment options and prepare a quotation.</p></div><Link className="btn btn-orange" href={quote}>Request a Quote</Link></div></section>
  </>;
}
function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) { return <section id={id} className="product-section"><h2>{title}</h2>{children}</section>; }
function InfoTable({ rows }: { rows: ReturnType<typeof visibleRows> }) { return <div className="table-wrap"><table><thead><tr><th>Item</th><th>Available Information</th></tr></thead><tbody>{rows.map((item) => <tr key={item.label}><th>{item.label}</th><td>{item.display}</td></tr>)}</tbody></table></div>; }
