import { Locale } from "./i18n";
export type Localized={title:string;summary:string;slug:string};
export type Product={id:string;family:string;model?:string;approvedImage?:{src:string;alt:Record<Locale,string>;ownershipStatus:"approved"};locales:Record<Locale,Localized>;applications:string[];principle:string;selection:string[];parameters:{label:string;value:string;status:"approved"}[]};
export const copy:Record<Locale,{nav:string[];tag:string;hero:string;intro:string;quote:string;details:string;explore:string}>={
 en:{nav:["Equipment","Industries","Solutions","Resources","About","Contact"],tag:"Practical magnetic separation",hero:"Specify the right separator without overspending",intro:"Clear equipment choices for bulk handling, minerals, recycling and process lines—based on your material and installation conditions.",quote:"Request a Quote",details:"Send Process Details",explore:"Explore equipment"},
 es:{nav:["Equipos","Industrias","Soluciones","Recursos","Nosotros","Contacto"],tag:"Separación magnética práctica",hero:"Defina el separador adecuado sin gastar de más",intro:"Opciones claras para materiales a granel, minerales, reciclaje y procesos, según el material y la instalación.",quote:"Solicitar cotización",details:"Enviar datos del proceso",explore:"Ver equipos"},
 pt:{nav:["Equipamentos","Indústrias","Soluções","Recursos","Sobre","Contato"],tag:"Separação magnética prática",hero:"Especifique o separador certo sem gastar além do necessário",intro:"Escolhas claras para granéis, minerais, reciclagem e processos, conforme o material e a instalação.",quote:"Solicitar cotação",details:"Enviar dados do processo",explore:"Ver equipamentos"},
 ar:{nav:["المعدات","الصناعات","الحلول","الموارد","من نحن","اتصل بنا"],tag:"فصل مغناطيسي عملي",hero:"حدد الفاصل المناسب دون إنفاق غير ضروري",intro:"خيارات واضحة لمناولة المواد والمعادن وإعادة التدوير وخطوط العمليات وفق ظروف المادة والتركيب.",quote:"اطلب عرض سعر",details:"أرسل بيانات العملية",explore:"استكشف المعدات"},
 ru:{nav:["Оборудование","Отрасли","Решения","Материалы","О нас","Контакты"],tag:"Практичная магнитная сепарация",hero:"Подберите сепаратор без лишних затрат",intro:"Понятный выбор для сыпучих материалов, минералов, переработки и технологических линий с учетом условий монтажа.",quote:"Запросить предложение",details:"Отправить параметры процесса",explore:"Смотреть оборудование"}
};
const loc=(en:string,es:string,pt:string,ar:string,ru:string,slugs:[string,string,string,string,string]):Record<Locale,Localized>=>({en:{title:en,summary:"Continuous removal of ferrous contamination from material moving on a conveyor.",slug:slugs[0]},es:{title:es,summary:"Retirada continua de contaminación ferrosa en transportadores.",slug:slugs[1]},pt:{title:pt,summary:"Remoção contínua de contaminantes ferrosos em transportadores.",slug:slugs[2]},ar:{title:ar,summary:"إزالة مستمرة للملوثات الحديدية من المواد على الناقل.",slug:slugs[3]},ru:{title:ru,summary:"Непрерывное удаление ферромагнитных включений с конвейера.",slug:slugs[4]}});
export const products:Product[]=[
 {id:"91b2c877-2f9d-4ab7-951d-f28b41e57b10",family:"conveyor",model:"PM-OV",locales:loc("Self-cleaning permanent overband separator","Separador permanente autolimpiante sobre banda","Separador permanente autolimpante sobre correia","فاصل دائم ذاتي التنظيف فوق الناقل","Самоочищающийся подвесной постоянный сепаратор",["self-cleaning-permanent-overband","separador-permanente-autolimpiante","separador-permanente-autolimpante","فاصل-دائم-ذاتي-التنظيف","самоочищающийся-подвесной-сепаратор"]),applications:["crusher protection","tramp-iron removal","ferrous recovery"],principle:"A suspended permanent magnetic circuit attracts ferrous pieces while a discharge belt carries collected metal away from the product stream.",selection:["belt width and speed","burden depth","suspension height","largest expected ferrous piece","duty cycle"],parameters:[{label:"Cleaning mode",value:"Continuous self-cleaning",status:"approved"}]},
 {id:"7c5911e4-d3dc-49b0-a21e-982e8cb284e0",family:"conveyor",model:"EM-OV",locales:loc("Self-cleaning electromagnetic overband separator","Separador electromagnético autolimpiante","Separador eletromagnético autolimpante","فاصل كهرومغناطيسي ذاتي التنظيف","Самоочищающийся электромагнитный сепаратор",["self-cleaning-electromagnetic-overband","separador-electromagnetico-autolimpiante","separador-eletromagnetico-autolimpante","فاصل-كهرومغناطيسي-ذاتي-التنظيف","электромагнитный-подвесной-сепаратор"]),applications:["heavy-duty conveyors","deep burden","crusher protection"],principle:"An energized coil creates the working magnetic field; an external belt continuously removes captured ferrous material.",selection:["belt width and speed","burden depth","available power","ambient conditions","cooling and duty cycle"],parameters:[{label:"Magnet type",value:"Electromagnetic",status:"approved"}]},
 {id:"e9940327-76f5-4a14-b657-d6a855062358",family:"minerals",model:"WD",locales:loc("Wet drum magnetic separator","Separador magnético de tambor húmedo","Separador magnético de tambor úmido","فاصل مغناطيسي بأسطوانة رطبة","Мокрый барабанный магнитный сепаратор",["wet-drum-mineral-separator","separador-tambor-humedo","separador-tambor-umido","فاصل-أسطواني-رطب","мокрый-барабанный-сепаратор"]),applications:["magnetic mineral recovery","slurry treatment","concentration"],principle:"A rotating drum presents a magnetic zone to slurry, retains responsive particles and releases them after leaving the field.",selection:["mineral response","particle size","solids concentration","throughput","washing arrangement"],parameters:[{label:"Process",value:"Wet",status:"approved"}]},
 {id:"0c126dd3-af43-4e67-8dbc-feb094485635",family:"recycling",model:"EC",locales:loc("Eddy current non-ferrous separator","Separador de corrientes de Foucault","Separador por correntes de Foucault","فاصل التيارات الدوامية للمعادن غير الحديدية","Вихретоковый сепаратор цветных металлов",["eddy-current-nonferrous-sorter","separador-corrientes-foucault","separador-correntes-foucault","فاصل-التيارات-الدوامية","вихретоковый-сепаратор"]),applications:["non-ferrous recovery","recycling","metal sorting"],principle:"A fast-changing magnetic field induces currents in conductive non-ferrous pieces, producing a repulsive sorting force.",selection:["material size distribution","feed presentation","target metals","throughput","upstream ferrous removal"],parameters:[{label:"Target",value:"Conductive non-ferrous metals",status:"approved"}]},
 {id:"5e0179ad-b3b8-4d75-9973-a17524ab2389",family:"process",model:"MG",locales:loc("Magnetic grate for gravity flow","Rejilla magnética para flujo por gravedad","Grade magnética para fluxo por gravidade","شبكة مغناطيسية للتدفق بالجاذبية","Магнитная решетка для самотека",["gravity-flow-magnetic-grate","rejilla-magnetica-gravedad","grade-magnetica-gravidade","شبكة-مغناطيسية-للجاذبية","магнитная-решетка-самотек"]),applications:["powders","granules","process protection"],principle:"Magnetic tubes intercept a gravity-fed material stream and capture ferrous particles at contact points.",selection:["material flowability","particle size","temperature","cleaning access","contact-material requirement"],parameters:[{label:"Flow",value:"Gravity-fed",status:"approved"}]}
];
export const families=[{key:"conveyor",slug:"conveyor-magnetic-separation",title:"Conveyor magnetic separation"},{key:"minerals",slug:"mineral-bulk-separation",title:"Mineral and bulk-material separation"},{key:"recycling",slug:"recycling-metal-sorting",title:"Recycling and metal sorting"},{key:"process",slug:"process-magnets-filters",title:"Process magnets and filters"}];
export const industries=["mining-minerals","coal-bulk-handling","aggregates-quarrying","cement-building-materials","recycling","food-grain"];
export const solutions=["crusher-protection","tramp-iron-removal","material-purity","ferrous-recovery","non-ferrous-sorting","fine-material-separation"];
export function productBySlug(locale:Locale,slug:string){return products.find(p=>p.locales[locale].slug===slug)}
