import type {Locale} from "./i18n";
export type VerifiedValue<T=string>={value:T;sourceId:string;conditions?:string;approvedAt:string};
export type Visibility="public"|"on_request"|"hidden";
export type ProductLocale={slug:string;title:string;summary:string;description:string;metaTitle:string;metaDescription:string;translatedAt?:string;reviewed:boolean};
export type ProductMedia={assetId:string;src:string;alt:Record<Locale,string>;isPrimary:boolean;type:"product"|"diagram";approved:boolean;aiGenerated:boolean};
export type ProductRecord={id:string;status:"draft"|"approved"|"published"|"archived";familyId:string;familyLabel:string;productType:string;verifiedName:string;media:ProductMedia[];applications:Array<{title:string;context:string;placement:string;material:string}>;capabilities:string[];selectionInputs:string[];specifications:Array<{label:string;value?:VerifiedValue;visibility:Visibility}>;options:Array<{label:string;value?:VerifiedValue;visibility:Visibility}>;limitations:string[];maintenance?:string[];faq:Array<{question:string;answer:string}>;relatedProductIds:string[];locale:Record<Locale,ProductLocale>};
export const equipmentSegments:Record<Locale,string>={en:"equipment",es:"equipos",pt:"equipamentos",ar:"المعدات",ru:"oborudovanie"};
export const productPath=(locale:Locale,slug:string)=>`/${locale}/${equipmentSegments[locale]}/${slug}`;
const locale=(slug:string,title:string,summary:string,description:string):ProductLocale=>({slug,title,summary,description,metaTitle:`${title} | BZMAGNET`,metaDescription:summary,translatedAt:"2026-08-13",reviewed:true});
export const productRecords:ProductRecord[]=[{
 id:"91b2c877-2f9d-4ab7-951d-f28b41e57b10",status:"published",familyId:"conveyor",familyLabel:"Conveyor Magnetic Separators",productType:"permanent-overband-self-cleaning",verifiedName:"Self-cleaning permanent overband separator",media:[],
 applications:[{title:"Conveyor protection",context:"Continuous bulk-material conveying",placement:"Suspended above the conveyor",material:"Bulk material with possible ferrous contamination"}],capabilities:["Continuous removal of ferrous contamination from conveyed material"],selectionInputs:["Material and particle-size range","Target ferrous contaminant","Belt width, speed and material layer depth","Throughput","Suspension position and available clearance","Ambient conditions","Project objective"],
 specifications:[{label:"Magnet type",value:{value:"Permanent magnetic circuit",sourceId:"bz-approved-fact-001",approvedAt:"2026-08-13"},visibility:"public"},{label:"Cleaning mode",value:{value:"Continuous self-cleaning",sourceId:"bz-approved-fact-002",approvedAt:"2026-08-13"},visibility:"public"},{label:"Dimensions",visibility:"on_request"},{label:"Installation position",value:{value:"Suspended above a conveyor",sourceId:"bz-approved-fact-003",approvedAt:"2026-08-13"},visibility:"public"}],options:[{label:"Project-specific configuration",visibility:"on_request"}],limitations:["Final suitability depends on the conveyed material, burden depth, target metal, belt conditions and available installation clearance."],faq:[{question:"What information is needed to review this separator?",answer:"Provide the material, particle size, belt width and speed, burden depth, throughput, target ferrous pieces and installation clearance."},{question:"Is the final configuration selected from the page alone?",answer:"No. The configuration is confirmed after the supplied process and installation information is reviewed."},{question:"Can dimensions be confirmed before quotation?",answer:"Dimensions are confirmed during technical discussion for the intended installation."}],relatedProductIds:[],
 locale:{en:locale("self-cleaning-permanent-overband","Self-cleaning Permanent Overband Separator","A suspended magnetic separation option for continuously removing ferrous contamination from material moving on a conveyor.","This equipment uses a permanent magnetic circuit above a conveyor while a discharge belt carries collected ferrous material away from the product stream."),es:locale("separador-permanente-autolimpiante-bz","Separador permanente autolimpiante sobre banda","Opción suspendida para retirar de forma continua contaminación ferrosa de material transportado.","El circuito magnético permanente se instala sobre el transportador y una banda de descarga retira el material ferroso capturado."),pt:locale("separador-permanente-autolimpante-bz","Separador permanente autolimpante sobre correia","Opção suspensa para remoção contínua de contaminação ferrosa em material transportado.","O circuito magnético permanente trabalha sobre a correia enquanto uma correia de descarga remove o material ferroso capturado."),ar:locale("فاصل-دائم-ذاتي-التنظيف-bz","فاصل دائم ذاتي التنظيف فوق الناقل","خيار فصل مغناطيسي معلق لإزالة الملوثات الحديدية باستمرار من المواد المنقولة.","تعمل الدائرة المغناطيسية الدائمة فوق الناقل بينما ينقل حزام التفريغ المواد الحديدية الملتقطة بعيداً عن تدفق المنتج."),ru:locale("samoochishchayushchiysya-postoyannyy-separator-bz","Самоочищающийся подвесной постоянный сепаратор","Подвесное решение для непрерывного удаления ферромагнитных включений с конвейера.","Постоянная магнитная система устанавливается над конвейером, а разгрузочная лента удаляет захваченный металл из потока.")}
}];
const denied=/cowin|TBD|Update Note|sourceClaims|```|manufacturer|guaranteed/i;
export function validateProductForPublication(p:ProductRecord){const errors:string[]=[];if(p.status!=="published")errors.push("status");if(!p.locale.en.title||!p.locale.en.slug)errors.push("english-required");for(const [code,value] of Object.entries(p.locale)){if(!value.title||!value.slug||!value.metaTitle||!value.metaDescription||!value.reviewed)errors.push(`locale-${code}`);if(denied.test(JSON.stringify(value)))errors.push(`public-copy-${code}`)}for(const media of p.media){if(media.type==="product"&&(!media.approved||media.aiGenerated))errors.push("product-image-approval")}for(const spec of [...p.specifications,...p.options])if(spec.visibility==="public"&&(!spec.value?.sourceId||!spec.value.approvedAt))errors.push(`unverified-${spec.label}`);if(p.faq.length>6||new Set(p.faq.map(x=>x.question.trim().toLowerCase())).size!==p.faq.length)errors.push("faq");const facts=JSON.stringify(p.specifications).toLowerCase();if(facts.includes("permanent")&&facts.includes("electromagnetic"))errors.push("magnet-conflict");return errors}
export const publicProducts=productRecords.filter(p=>validateProductForPublication(p).length===0);
export function findProduct(locale:Locale,slug:string){let decoded=slug;try{decoded=decodeURIComponent(slug)}catch{}return publicProducts.find(p=>p.locale[locale].slug===decoded)}
export function visibleRows(rows:ProductRecord["specifications"]){return rows.filter(x=>x.visibility!=="hidden").map(x=>({...x,display:x.visibility==="on_request"?"Available on request":x.value?.conditions?`${x.value.value} — ${x.value.conditions}`:x.value?.value||"Available on request"}))}
