import type { Locale } from "./i18n";

type UiCopy = {
  listing: { solution: string; industry: string; intro: string; description: string; open: string };
  context: {
    industry: string; solution: string; intro: string; dutyTitle: string; dutyText: string;
    installationTitle: string; installationText: string; validateTitle: string; validateText: string;
    enquiryTitle: string; enquiryText: string; send: string;
  };
  footer: {
    description: string; equipment: string; industries: string; news: string; blog: string;
    about: string; quote: string; copyright: string; privacy: string; terms: string;
    equipmentLinks: string[]; industryLinks: string[];
  };
  article: {
    home: string; news: string; blog: string; companyNews: string; industryNews: string;
    breadcrumb: string; updated: string; onPage: string; sources: string; unavailableDate: string;
    checked: string; faq: string; related: string;
  };
  resources: { eyebrow: string; intro: string; guide: string; description: string; items: string[] };
  policy: { eyebrow: string; title: string; intro: string; paragraphs: string[] };
  author: { eyebrow: string; title: string; intro: string; body: string };
  news: { companyEyebrow: string; companyTitle: string; companyEmpty: string; industryEyebrow: string; industryTitle: string; industryEmpty: string };
  approvedRecords: (count: number) => string;
};

export const uiCopy: Record<Locale, UiCopy> = {
  en: {
    listing: { solution: "Solutions", industry: "Industries", intro: "Use the process context to narrow the equipment family before discussing a model.", description: "Define material, target contaminant, throughput and installation constraints for this application.", open: "Open guidance" },
    context: { industry: "Industry", solution: "Solution", intro: "Build the selection around verified process conditions and the required separation objective.", dutyTitle: "Define the duty", dutyText: "Confirm the feed material, particle-size range, target metal or contaminant, nominal and peak throughput, and the desired downstream result.", installationTitle: "Check the installation", installationText: "Provide conveyor, chute or pipe dimensions, speed, available space, environment, electrical requirements and cleaning constraints.", validateTitle: "Validate before purchase", validateText: "Final suitability depends on representative material data and an agreed configuration. Unknown parameters remain unpublished until approved.", enquiryTitle: "Prepare a useful enquiry", enquiryText: "Send photos, a process sketch and operating data where available.", send: "Send process details" },
    footer: { description: "Product sourcing, application-focused communication and export coordination for industrial magnetic separation equipment.", equipment: "Equipment", industries: "Industry Solutions", news: "News", blog: "Blog", about: "About & Contact", quote: "Request a Quote", copyright: "Equipment configuration depends on confirmed application details.", privacy: "Privacy Policy", terms: "Terms", equipmentLinks: ["Conveyor Magnetic Separators", "Mineral & Bulk Separation", "Recycling & Metal Sorting", "Process Magnets & Filters"], industryLinks: ["Mining & Minerals", "Cement & Aggregates", "Recycling", "Coal & Bulk Handling"] },
    article: { home: "Home", news: "News", blog: "Blog", companyNews: "Company news", industryNews: "Industry news", breadcrumb: "Breadcrumb", updated: "Updated", onPage: "On this page", sources: "Sources & verification", unavailableDate: "date not available", checked: "checked", faq: "Frequently Asked Questions", related: "Related equipment" },
    resources: { eyebrow: "Resources", intro: "Procurement notes written for practical technical comparison.", guide: "GUIDE", description: "Structured guidance with visible facts, review status and no placeholder sections.", items: ["Separator selection checklist", "Conveyor data worksheet", "Material-test preparation", "Maintenance planning questions"] },
    policy: { eyebrow: "Policy", title: "Technical content and review policy", intro: "How BZMAGNET reviews public technical content.", paragraphs: ["Public technical statements must be traceable to approved BZMAGNET source data. Editors separate product facts from guidance, mark unknown fields, review translations and remove unsupported claims.", "Articles identify their review status and are updated when verified information changes."] },
    author: { eyebrow: "Editorial", title: "BZMAGNET Editorial Team", intro: "Editorial information for BZMAGNET readers.", body: "BZMAGNET publishes product-sourcing guidance and verified business updates. Content is reviewed against approved product records, stated source requirements and the organization’s accuracy policy." },
    news: { companyEyebrow: "BZMAGNET updates", companyTitle: "Company News", companyEmpty: "No verified company news is published in this language.", industryEyebrow: "Source-reviewed developments", industryTitle: "Industry News", industryEmpty: "No source-reviewed industry news is published in this language." },
    approvedRecords: (count) => `${count} approved equipment records`,
  },
  es: {
    listing: { solution: "Soluciones", industry: "Industrias", intro: "Use el contexto del proceso para acotar la familia de equipos antes de analizar un modelo.", description: "Defina el material, el contaminante objetivo, el caudal y las limitaciones de instalación.", open: "Abrir guía" },
    context: { industry: "Industria", solution: "Solución", intro: "Base la selección en condiciones de proceso verificadas y en el objetivo de separación requerido.", dutyTitle: "Definir la función", dutyText: "Confirme el material de alimentación, el tamaño de partícula, el metal o contaminante objetivo, el caudal nominal y máximo y el resultado deseado.", installationTitle: "Comprobar la instalación", installationText: "Indique dimensiones y velocidad de la cinta, canal o tubería, espacio disponible, entorno, requisitos eléctricos y limitaciones de limpieza.", validateTitle: "Validar antes de comprar", validateText: "La idoneidad final depende de datos representativos del material y de una configuración acordada. Los parámetros desconocidos no se publican hasta su aprobación.", enquiryTitle: "Preparar una consulta útil", enquiryText: "Envíe fotos, un esquema del proceso y datos de operación cuando estén disponibles.", send: "Enviar datos del proceso" },
    footer: { description: "Suministro de productos, comunicación centrada en la aplicación y coordinación de exportación para equipos industriales de separación magnética.", equipment: "Equipos", industries: "Soluciones industriales", news: "Noticias", blog: "Blog", about: "Nosotros y contacto", quote: "Solicitar cotización", copyright: "La configuración depende de los datos confirmados de la aplicación.", privacy: "Política de privacidad", terms: "Términos", equipmentLinks: ["Separadores magnéticos para cintas", "Separación de minerales y graneles", "Reciclaje y clasificación de metales", "Imanes y filtros de proceso"], industryLinks: ["Minería y minerales", "Cemento y áridos", "Reciclaje", "Carbón y graneles"] },
    article: { home: "Inicio", news: "Noticias", blog: "Blog", companyNews: "Noticias de la empresa", industryNews: "Noticias del sector", breadcrumb: "Migas de pan", updated: "Actualizado", onPage: "En esta página", sources: "Fuentes y verificación", unavailableDate: "fecha no disponible", checked: "consultado", faq: "Preguntas frecuentes", related: "Equipos relacionados" },
    resources: { eyebrow: "Recursos", intro: "Notas de compra para una comparación técnica práctica.", guide: "GUÍA", description: "Orientación estructurada con datos visibles, estado de revisión y sin secciones de relleno.", items: ["Lista para seleccionar un separador", "Hoja de datos de la cinta", "Preparación de pruebas de material", "Preguntas para planificar el mantenimiento"] },
    policy: { eyebrow: "Política", title: "Política de contenido técnico y revisión", intro: "Cómo revisa BZMAGNET el contenido técnico público.", paragraphs: ["Las afirmaciones técnicas públicas deben poder rastrearse hasta datos aprobados de BZMAGNET. Los editores separan los datos de producto de la orientación, marcan los campos desconocidos, revisan las traducciones y eliminan afirmaciones sin respaldo.", "Los artículos muestran su estado de revisión y se actualizan cuando cambia información verificada."] },
    author: { eyebrow: "Editorial", title: "Equipo editorial de BZMAGNET", intro: "Información editorial para los lectores de BZMAGNET.", body: "BZMAGNET publica orientación para el suministro de productos y novedades empresariales verificadas. El contenido se revisa con los registros de producto aprobados, los requisitos de las fuentes y la política de precisión de la organización." },
    news: { companyEyebrow: "Actualizaciones de BZMAGNET", companyTitle: "Noticias de la empresa", companyEmpty: "No hay noticias verificadas de la empresa publicadas en este idioma.", industryEyebrow: "Novedades revisadas con fuentes", industryTitle: "Noticias del sector", industryEmpty: "No hay noticias del sector revisadas con fuentes en este idioma." },
    approvedRecords: (count) => `${count} registros de equipos aprobados`,
  },
  pt: {
    listing: { solution: "Soluções", industry: "Setores", intro: "Use o contexto do processo para restringir a família de equipamentos antes de discutir um modelo.", description: "Defina o material, o contaminante-alvo, a vazão e as restrições de instalação.", open: "Abrir orientação" },
    context: { industry: "Setor", solution: "Solução", intro: "Baseie a seleção nas condições verificadas do processo e no objetivo de separação necessário.", dutyTitle: "Defina a função", dutyText: "Confirme o material de alimentação, a faixa granulométrica, o metal ou contaminante-alvo, a vazão nominal e máxima e o resultado desejado.", installationTitle: "Verifique a instalação", installationText: "Informe dimensões e velocidade da correia, calha ou tubo, espaço disponível, ambiente, requisitos elétricos e restrições de limpeza.", validateTitle: "Valide antes da compra", validateText: "A adequação final depende de dados representativos do material e de uma configuração acordada. Parâmetros desconhecidos não são publicados até a aprovação.", enquiryTitle: "Prepare uma consulta útil", enquiryText: "Envie fotos, um esquema do processo e dados operacionais quando disponíveis.", send: "Enviar dados do processo" },
    footer: { description: "Fornecimento de produtos, comunicação focada na aplicação e coordenação de exportação para equipamentos industriais de separação magnética.", equipment: "Equipamentos", industries: "Soluções industriais", news: "Notícias", blog: "Blog", about: "Sobre e contato", quote: "Solicitar cotação", copyright: "A configuração depende dos dados confirmados da aplicação.", privacy: "Política de privacidade", terms: "Termos", equipmentLinks: ["Separadores magnéticos para transportadores", "Separação mineral e de granéis", "Reciclagem e classificação de metais", "Ímãs e filtros de processo"], industryLinks: ["Mineração e minerais", "Cimento e agregados", "Reciclagem", "Carvão e granéis"] },
    article: { home: "Início", news: "Notícias", blog: "Blog", companyNews: "Notícias da empresa", industryNews: "Notícias do setor", breadcrumb: "Navegação estrutural", updated: "Atualizado", onPage: "Nesta página", sources: "Fontes e verificação", unavailableDate: "data indisponível", checked: "consultado", faq: "Perguntas frequentes", related: "Equipamentos relacionados" },
    resources: { eyebrow: "Recursos", intro: "Notas de aquisição para comparação técnica prática.", guide: "GUIA", description: "Orientação estruturada com dados visíveis, status de revisão e sem seções de preenchimento.", items: ["Lista para seleção de separador", "Planilha de dados do transportador", "Preparação do teste de material", "Perguntas para planejar a manutenção"] },
    policy: { eyebrow: "Política", title: "Política de conteúdo técnico e revisão", intro: "Como a BZMAGNET revisa o conteúdo técnico público.", paragraphs: ["As declarações técnicas públicas devem ser rastreáveis aos dados aprovados da BZMAGNET. Os editores separam fatos de produto de orientações, marcam campos desconhecidos, revisam traduções e removem afirmações sem suporte.", "Os artigos indicam seu status de revisão e são atualizados quando informações verificadas mudam."] },
    author: { eyebrow: "Editorial", title: "Equipe editorial BZMAGNET", intro: "Informações editoriais para leitores da BZMAGNET.", body: "A BZMAGNET publica orientações de fornecimento de produtos e atualizações comerciais verificadas. O conteúdo é revisado com base em registros aprovados de produtos, requisitos declarados das fontes e na política de precisão da organização." },
    news: { companyEyebrow: "Atualizações da BZMAGNET", companyTitle: "Notícias da empresa", companyEmpty: "Não há notícias verificadas da empresa publicadas neste idioma.", industryEyebrow: "Desenvolvimentos revisados por fontes", industryTitle: "Notícias do setor", industryEmpty: "Não há notícias do setor revisadas por fontes neste idioma." },
    approvedRecords: (count) => `${count} registros de equipamentos aprovados`,
  },
  ar: {
    listing: { solution: "الحلول", industry: "الصناعات", intro: "استخدم سياق العملية لتضييق نطاق عائلة المعدات قبل مناقشة طراز محدد.", description: "حدّد المادة والملوث المستهدف والإنتاجية وقيود التركيب لهذا التطبيق.", open: "فتح الدليل" },
    context: { industry: "الصناعة", solution: "الحل", intro: "ابنِ الاختيار على ظروف عملية موثقة وهدف الفصل المطلوب.", dutyTitle: "حدّد المهمة", dutyText: "أكد مادة التغذية ونطاق حجم الجسيمات والمعدن أو الملوث المستهدف والإنتاجية الاسمية والقصوى والنتيجة المطلوبة.", installationTitle: "تحقق من التركيب", installationText: "قدّم أبعاد وسرعة السير أو المجرى أو الأنبوب والمساحة المتاحة والبيئة والمتطلبات الكهربائية وقيود التنظيف.", validateTitle: "تحقق قبل الشراء", validateText: "تعتمد الملاءمة النهائية على بيانات ممثلة للمادة وتهيئة متفق عليها. لا تُنشر المعلمات غير المعروفة حتى اعتمادها.", enquiryTitle: "جهّز استفساراً مفيداً", enquiryText: "أرسل الصور ومخطط العملية وبيانات التشغيل عند توفرها.", send: "أرسل تفاصيل العملية" },
    footer: { description: "توريد المنتجات والتواصل المرتكز على التطبيق وتنسيق التصدير لمعدات الفصل المغناطيسي الصناعية.", equipment: "المعدات", industries: "حلول الصناعات", news: "الأخبار", blog: "المدونة", about: "نبذة واتصال", quote: "اطلب عرض سعر", copyright: "تعتمد تهيئة المعدات على تفاصيل التطبيق المؤكدة.", privacy: "سياسة الخصوصية", terms: "الشروط", equipmentLinks: ["فواصل مغناطيسية للسيور", "فصل المعادن والمواد السائبة", "إعادة التدوير وفرز المعادن", "مغناطيسات وفلاتر العمليات"], industryLinks: ["التعدين والمعادن", "الأسمنت والركام", "إعادة التدوير", "الفحم والمواد السائبة"] },
    article: { home: "الرئيسية", news: "الأخبار", blog: "المدونة", companyNews: "أخبار الشركة", industryNews: "أخبار الصناعة", breadcrumb: "مسار التنقل", updated: "محدّث", onPage: "في هذه الصفحة", sources: "المصادر والتحقق", unavailableDate: "التاريخ غير متاح", checked: "تم التحقق", faq: "الأسئلة الشائعة", related: "معدات ذات صلة" },
    resources: { eyebrow: "الموارد", intro: "ملاحظات شراء للمقارنة الفنية العملية.", guide: "دليل", description: "إرشادات منظمة ببيانات ظاهرة وحالة مراجعة ومن دون أقسام مؤقتة.", items: ["قائمة اختيار الفاصل", "ورقة بيانات السير", "التحضير لاختبار المادة", "أسئلة تخطيط الصيانة"] },
    policy: { eyebrow: "السياسة", title: "سياسة المحتوى الفني والمراجعة", intro: "كيفية مراجعة BZMAGNET للمحتوى الفني العام.", paragraphs: ["يجب أن تكون التصريحات الفنية العامة قابلة للتتبع إلى بيانات BZMAGNET المعتمدة. يفصل المحررون حقائق المنتج عن الإرشادات، ويحددون الحقول غير المعروفة، ويراجعون الترجمات ويحذفون الادعاءات غير المدعومة.", "توضح المقالات حالة مراجعتها وتُحدّث عند تغير المعلومات الموثقة."] },
    author: { eyebrow: "التحرير", title: "فريق تحرير BZMAGNET", intro: "معلومات تحريرية لقراء BZMAGNET.", body: "تنشر BZMAGNET إرشادات توريد المنتجات وتحديثات أعمال موثقة. يُراجع المحتوى مقابل سجلات المنتجات المعتمدة ومتطلبات المصادر المعلنة وسياسة الدقة لدى المؤسسة." },
    news: { companyEyebrow: "تحديثات BZMAGNET", companyTitle: "أخبار الشركة", companyEmpty: "لا توجد أخبار شركة موثقة منشورة بهذه اللغة.", industryEyebrow: "تطورات مراجعة بالمصادر", industryTitle: "أخبار الصناعة", industryEmpty: "لا توجد أخبار صناعة مراجعة بالمصادر منشورة بهذه اللغة." },
    approvedRecords: (count) => `${count} سجل معدات معتمد`,
  },
  ru: {
    listing: { solution: "Решения", industry: "Отрасли", intro: "Используйте условия процесса, чтобы сузить семейство оборудования до обсуждения модели.", description: "Укажите материал, целевое загрязнение, производительность и ограничения монтажа.", open: "Открыть руководство" },
    context: { industry: "Отрасль", solution: "Решение", intro: "Стройте подбор на проверенных условиях процесса и требуемой цели сепарации.", dutyTitle: "Определите задачу", dutyText: "Укажите исходный материал, диапазон размера частиц, целевой металл или загрязнение, номинальную и пиковую производительность и желаемый результат.", installationTitle: "Проверьте монтаж", installationText: "Сообщите размеры и скорость конвейера, желоба или трубы, доступное пространство, условия среды, электропитание и ограничения очистки.", validateTitle: "Проверьте до покупки", validateText: "Окончательная пригодность зависит от репрезентативных данных материала и согласованной конфигурации. Неизвестные параметры не публикуются до утверждения.", enquiryTitle: "Подготовьте полезный запрос", enquiryText: "Приложите фотографии, схему процесса и рабочие данные, если они доступны.", send: "Отправить данные процесса" },
    footer: { description: "Подбор продукции, коммуникация по применению и координация экспорта промышленного магнитного сепарационного оборудования.", equipment: "Оборудование", industries: "Отраслевые решения", news: "Новости", blog: "Блог", about: "О компании и контакты", quote: "Запросить предложение", copyright: "Конфигурация зависит от подтвержденных данных применения.", privacy: "Политика конфиденциальности", terms: "Условия", equipmentLinks: ["Конвейерные магнитные сепараторы", "Сепарация минералов и сыпучих материалов", "Переработка и сортировка металлов", "Технологические магниты и фильтры"], industryLinks: ["Горная промышленность", "Цемент и заполнители", "Переработка", "Уголь и сыпучие материалы"] },
    article: { home: "Главная", news: "Новости", blog: "Блог", companyNews: "Новости компании", industryNews: "Новости отрасли", breadcrumb: "Навигационная цепочка", updated: "Обновлено", onPage: "На этой странице", sources: "Источники и проверка", unavailableDate: "дата недоступна", checked: "проверено", faq: "Часто задаваемые вопросы", related: "Связанное оборудование" },
    resources: { eyebrow: "Материалы", intro: "Закупочные заметки для практического технического сравнения.", guide: "РУКОВОДСТВО", description: "Структурированное руководство с видимыми фактами, статусом проверки и без временных разделов.", items: ["Список для выбора сепаратора", "Форма данных конвейера", "Подготовка испытания материала", "Вопросы планирования обслуживания"] },
    policy: { eyebrow: "Политика", title: "Политика технического контента и проверки", intro: "Как BZMAGNET проверяет общедоступный технический контент.", paragraphs: ["Публичные технические утверждения должны прослеживаться до утвержденных данных BZMAGNET. Редакторы отделяют факты о продукции от рекомендаций, отмечают неизвестные поля, проверяют переводы и удаляют неподтвержденные заявления.", "В статьях указан статус проверки; они обновляются при изменении проверенной информации."] },
    author: { eyebrow: "Редакция", title: "Редакция BZMAGNET", intro: "Редакционная информация для читателей BZMAGNET.", body: "BZMAGNET публикует рекомендации по подбору продукции и проверенные деловые обновления. Контент проверяется по утвержденным данным о продукции, заявленным требованиям к источникам и политике точности организации." },
    news: { companyEyebrow: "Обновления BZMAGNET", companyTitle: "Новости компании", companyEmpty: "Проверенные новости компании на этом языке пока не опубликованы.", industryEyebrow: "События, проверенные по источникам", industryTitle: "Новости отрасли", industryEmpty: "Проверенные по источникам отраслевые новости на этом языке пока не опубликованы." },
    approvedRecords: (count) => `${count} утвержденных записей оборудования`,
  },
};
